services:
  web:
    build:
      context: ./web  
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/PersonDatabase

  db:
    build:
      context: ./db  
      dockerfile: Dockerfile  
    ports:
      - "27017:27017"